"""
This type stub file was generated by pyright.
"""

from typing import Any
from .models.containers import ContainerCollection

class DockerClient:
    @classmethod
    def from_env(cls, **kwargs: dict[str, Any]) -> DockerClient: ...
    @property
    def containers(self) -> ContainerCollection: ...

from_env = DockerClient.from_env
