default_language_version:
  python: python3.12
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v2.3.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
        exclude: '^authelia-configs/'
      - id: end-of-file-fixer
      - id: name-tests-test
        exclude: '^tests/shared.py'
      - id: pretty-format-json
        args: [ --autofix ]
      - id: sort-simple-yaml
      - id: trailing-whitespace
  - repo: 'https://github.com/astral-sh/ruff-pre-commit'
    rev: v0.3.5
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.361
    hooks:
    - id: pyright
      additional_dependencies:
        # From poetry.lock
        - 'docker==7.0.0'
        - 'git+https://github.com/rdozier-work/docker-stubs@9de7906804ae912f1d644c97b617ac77e784fca8'
        - 'hypothesis==6.100.0'
        - 'loguru==0.7.2'
        - 'pytest==8.1.1'
        - 'ruamel-yaml==0.18.6'
        - 'typer==0.12.0'
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.2
    hooks:
      - id: poetry-check
      - id: poetry-export
