"""
This type stub file was generated by pyright.
"""

from typing import Any

class Container:
    @property
    def name(self) -> str: ...
    @property
    def labels(self) -> dict[str, str]: ...
    def restart(self, **kwargs: dict[str, Any]) -> None: ...

class ContainerCollection:
    def list(self) -> list[Container]: ...
