services:
  dl2ac:
    build:
      context: ..
      dockerfile: "./docker/Dockerfile"
    environment:
      - DOCKER_HOST=tcp://docker-proxy:2375
      - SLEEP_AT_START_N_SECONDS
    networks:
      - proxy
    profiles: [dev-docker]
    user: 1000:1000
    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../dev/docker/config:/config
      - ../dev/docker/rules:/rules

  docker-proxy:
    image: tecnativa/docker-socket-proxy
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - LOG_LEVEL=warning
      - CONTAINERS=1
      - POST=1

  authelia:
    image: containous/whoami
    labels:
      - "dl2ac.is-authelia=true"

  whoami1:
    image: containous/whoami
    labels:
      dl2ac.rules.one.domain.1: '*.example.com'
      dl2ac.rules.one.domain_traefik.1: whoami1-router
      # Please note that regular expressions in this label format require
      # Single backslash and use of single quotes
      dl2ac.rules.one.domain_regex.1: '^user-(?P<User>\w+)\.example\.com$'
      dl2ac.rules.one.domain_regex.2: '^group-(?P<Group>\w+)\.example\.com$'
      dl2ac.rules.one.methods.1: GET
      dl2ac.rules.one.methods.2: POST
      dl2ac.rules.one.networks.1: 172.16.0.0/12
      dl2ac.rules.one.networks.2: 192.168.0.0/18
      dl2ac.rules.one.networks.3: internal1
      dl2ac.rules.one.policy: one_factor
      dl2ac.rules.one.query.1.1.key: token
      dl2ac.rules.one.query.1.1.operator: not pattern
      # Please note that regular expressions in this label format require
      # Single backslash and use of single quotes
      dl2ac.rules.one.query.1.1.value: '^(abc123|zyx789)$'
      dl2ac.rules.one.query.2.1.key: secure
      dl2ac.rules.one.query.2.2.key: insecure
      dl2ac.rules.one.query.2.2.operator: absent
      dl2ac.rules.one.query.3.1.key: random
      dl2ac.rules.one.query.3.1.value: 123
      dl2ac.rules.one.rank: 10
      # Please note that regular expressions in this label format require
      # Single backslash and use of single quotes
      dl2ac.rules.one.resources.1: '^/api([/?].*)?$'
      dl2ac.rules.one.subject.1.1: user:john
      dl2ac.rules.one.subject.2.1: group:admin
      dl2ac.rules.one.subject.2.2: group:app-name
      dl2ac.rules.one.subject.3.1: group:super-admin
      traefik.http.routers.whoami1-router.middlewares: 'authelia@docker'
      traefik.http.routers.whoami1-router.rule: 'Host(`whoami1.example.com`)'

  whoami2:
    image: containous/whoami
    labels:
      - "dl2ac.rules.two.domain.1=*.example.com"
      - "dl2ac.rules.two.domain_traefik.1=whoami2-router"
      # Please note that regular expressions in this label format require
      # Double backslash and use of no quotes
      - "dl2ac.rules.two.domain_regex.1=^user-(?P<User>\\w+)\\.example\\.com$"
      - "dl2ac.rules.two.domain_regex.2=^group-(?P<Group>\\w+)\\.example\\.com$"
      - "dl2ac.rules.two.methods.1=GET"
      - "dl2ac.rules.two.methods.2=POST"
      - "dl2ac.rules.two.methods.2=POST"
      - "dl2ac.rules.two.networks.1=172.16.0.0/12"
      - "dl2ac.rules.two.networks.2=192.168.0.0/18"
      - "dl2ac.rules.two.networks.3=internal2"
      - "dl2ac.rules.two.policy=one_factor"
      - "dl2ac.rules.two.query.1.1.key=token"
      - "dl2ac.rules.two.query.1.1.operator=not pattern"
      # Please note that regular expressions in this label format require
      # Double backslash and use of no quotes
      - "dl2ac.rules.two.query.1.1.value=^(abc123|zyx789)$"
      - "dl2ac.rules.two.query.2.1.key=secure"
      - "dl2ac.rules.two.query.2.2.key=insecure"
      - "dl2ac.rules.two.query.2.2.operator=absent"
      - "dl2ac.rules.two.query.3.1.key=random"
      - "dl2ac.rules.two.query.3.1.value=123"
      - "dl2ac.rules.two.rank=20"
      # Please note that regular expressions in this label format require
      # Double backslash and use of no quotes
      - "dl2ac.rules.two.resources.1=^/api([/?].*)?$"
      - "dl2ac.rules.two.subject.1.1=user:john"
      - "dl2ac.rules.two.subject.2.1=group:admin"
      - "dl2ac.rules.two.subject.2.2=group:app-name"
      - "dl2ac.rules.two.subject.3.1=group:super-admin"
      - "traefik.http.routers.whoami2-router.middlewares=authelia@docker"
      - "traefik.http.routers.whoami2-router.rule=Host(`whoami2.example.com`)"

networks:
  proxy:
