default_policy: deny
rules:
- name: one
  methods:
  - GET
  - POST
  policy: one_factor
  resources:
  - '^/api([/?].*)?$'
  subject:
  - user:john
  - - group:admin
    - group:app-name
  - group:super-admin
