services:
  dl2ac:
    build:
      context: ..
      dockerfile: "./docker/Dockerfile"
    environment:
      - DOCKER_HOST=tcp://docker-proxy:2375
      - SLEEP_AT_START_N_SECONDS
    networks:
      - proxy
    profiles: [dev-docker]
    user: 1000:1000
    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../dev/docker/config:/config
      - ../dev/docker/rules:/rules

  docker-proxy:
    image: tecnativa/docker-socket-proxy
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - LOG_LEVEL=warning
      - CONTAINERS=1
      - POST=1

  authelia:
    image: containous/whoami
    labels:
      - "dl2ac.is-authelia=true"

  whoami:
    image: containous/whoami
    labels:
      - "dl2ac.rules.one.domain.1=*.example.com"
      - "dl2ac.rules.one.methods.1=GET"
      - "dl2ac.rules.one.methods.2=POST"
      - "dl2ac.rules.one.methods.2=POST"
      - "dl2ac.rules.one.policy=one_factor"
      - "dl2ac.rules.one.rank=20"
      - "dl2ac.rules.one.resources.1=^/api([/?].*)?$"
      - "dl2ac.rules.one.subject.1.1=user:john"
      - "dl2ac.rules.one.subject.2.1=group:admin"
      - "dl2ac.rules.one.subject.2.2=group:app-name"
      - "dl2ac.rules.one.subject.3.1=group:super-admin"

networks:
  proxy:
