version: "3.7"

services:
  authelia:
    image: containous/whoami
    labels:
      - "dl2ac.is-authelia=true"

  whoami:
    image: containous/whoami
    labels:
      - "dl2ac.rules.one.priority=20"
      - "dl2ac.rules.one.policy=one_factor"
