default_policy: deny
rules:
- name: one
  domain:
  - '*.example.com'
  - whoami1.example.com
  domain_regex:
  - ^user-(?P<User>\w+)\.example\.com$
  - ^group-(?P<Group>\w+)\.example\.com$
  methods:
  - GET
  - POST
  policy: one_factor
  resources:
  - ^/api([/?].*)?$
  query:
  - key: token
    operator: not pattern
  - - key: secure
    - key: insecure
      operator: absent
  - key: random
    value: '123'
  subject:
  - user:john
  - - group:admin
    - group:app-name
  - group:super-admin
- name: two
  domain:
  - '*.example.com'
  - whoami2.example.com
  domain_regex:
  - ^user-(?P<User>\w+)\.example\.com$
  - ^group-(?P<Group>\w+)\.example\.com$
  methods:
  - GET
  - POST
  policy: one_factor
  resources:
  - ^/api([/?].*)?$
  query:
  - key: token
    operator: not pattern
  - - key: secure
    - key: insecure
      operator: absent
  - key: random
    value: '123'
  subject:
  - user:john
  - - group:admin
    - group:app-name
  - group:super-admin
